/* soapSoapServiceSoapBindingProxy.cpp
   Generated by gSOAP 2.8.70 for lbmriskwarning.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapSoapServiceSoapBindingProxy.h"

SoapServiceSoapBindingProxy::SoapServiceSoapBindingProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	SoapServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

SoapServiceSoapBindingProxy::SoapServiceSoapBindingProxy(const SoapServiceSoapBindingProxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

SoapServiceSoapBindingProxy::SoapServiceSoapBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	SoapServiceSoapBindingProxy_init(_soap->imode, _soap->omode);
}

SoapServiceSoapBindingProxy::SoapServiceSoapBindingProxy(struct soap *_soap, const char *endpoint)
{	this->soap = _soap;
	this->soap_own = false;
	SoapServiceSoapBindingProxy_init(_soap->imode, _soap->omode);
	soap_endpoint = endpoint;
}

SoapServiceSoapBindingProxy::SoapServiceSoapBindingProxy(const char *endpoint)
{	this->soap = soap_new();
	this->soap_own = true;
	SoapServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = endpoint;
}

SoapServiceSoapBindingProxy::SoapServiceSoapBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	SoapServiceSoapBindingProxy_init(iomode, iomode);
}

SoapServiceSoapBindingProxy::SoapServiceSoapBindingProxy(const char *endpoint, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	SoapServiceSoapBindingProxy_init(iomode, iomode);
	soap_endpoint = endpoint;
}

SoapServiceSoapBindingProxy::SoapServiceSoapBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	SoapServiceSoapBindingProxy_init(imode, omode);
}

SoapServiceSoapBindingProxy::~SoapServiceSoapBindingProxy()
{	if (this->soap_own)
		soap_free(this->soap);
}

void SoapServiceSoapBindingProxy::SoapServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
        {"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"ns1", "http://soap.szkingdom.com/", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this->soap, namespaces);
}

SoapServiceSoapBindingProxy *SoapServiceSoapBindingProxy::copy()
{	SoapServiceSoapBindingProxy *dup = SOAP_NEW_UNMANAGED(SoapServiceSoapBindingProxy);
	if (dup)
	{	soap_done(dup->soap);
		soap_copy_context(dup->soap, this->soap);
	}
	return dup;
}

SoapServiceSoapBindingProxy& SoapServiceSoapBindingProxy::operator=(const SoapServiceSoapBindingProxy& rhs)
{	if (this->soap != rhs.soap)
	{	if (this->soap_own)
			soap_free(this->soap);
		this->soap = rhs.soap;
		this->soap_own = false;
		this->soap_endpoint = rhs.soap_endpoint;
	}
	return *this;
}

void SoapServiceSoapBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void SoapServiceSoapBindingProxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	SoapServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void SoapServiceSoapBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

::SOAP_ENV__Header *SoapServiceSoapBindingProxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *SoapServiceSoapBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *SoapServiceSoapBindingProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *SoapServiceSoapBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int SoapServiceSoapBindingProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int SoapServiceSoapBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void SoapServiceSoapBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void SoapServiceSoapBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *SoapServiceSoapBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int SoapServiceSoapBindingProxy::doService(const char *endpoint, const char *soap_action, ns1__doService *ns1__doService_, ns1__doServiceResponse &ns1__doServiceResponse_)
{
	struct __ns1__doService soap_tmp___ns1__doService;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.50.98:8081/kdbi/services/SoapService";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__doService.ns1__doService_ = ns1__doService_;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__doService(soap, &soap_tmp___ns1__doService);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__doService(soap, &soap_tmp___ns1__doService, "-ns1:doService", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__doService(soap, &soap_tmp___ns1__doService, "-ns1:doService", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<ns1__doServiceResponse*>(&ns1__doServiceResponse_)) // NULL ref?
		return soap_closesock(soap);
	ns1__doServiceResponse_.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__doServiceResponse_.soap_get(soap, "ns1:doServiceResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
